# Generated by Django 4.1 on 2022-08-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="extendeduser",
            name="id_token_claims",
            field=models.TextField(blank=True, default=""),
        ),
    ]
