# jekyll-rtd-theme
# https://github.com/rundocs/jekyll-rtd-theme

remote_theme: rundocs/jekyll-rtd-theme

# Aux links for the upper right navigation
aux_links:
  "View PyPi package":
    - "//pypi.org/project/django-azure-active-directory-signin/"