# Just the Docs
# A modern, highly customizable, and responsive Jekyll theme for documentation with built-in search.
# https://github.com/just-the-docs/just-the-docs

remote_theme: rundocs/jekyll-rtd-theme

# Aux links for the upper right navigation
aux_links:
  "View PyPi package":
    - "//pypi.org/project/django-azure-active-directory-signin/"