remote_theme: https://github.com/JV-conseil/read-the-docs-jekyll-theme

# Aux links for the upper right navigation
aux_links:
  "View PyPi package":
    - "//pypi.org/project/django-azure-active-directory-signin/"
